version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Europe/Moscow'
    volumes:
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql"
  web:
    image: duaneleem/live-server:1.0
    ports:
      - 8080:8080
    volumes:
      - "./client:/usr/src/app"
